name: Testing Actions on PR

on:
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-20.04
    steps:
      - name: "Say hi"
        run: echo "Hello!"

      - name: "Expose secret"
        shell: bash
        env:
          A_BIG_SECRET: ${{ secrets.A_BIG_SECRET }}
          SOME_OTHER_SECRET: ${{ secrets.SOME_OTHER_SECRET }}
          AN_ENV_VAR: ${{ secrets.SOME_OTHER_SECRET }}
        run: |
          echo "$SOME_OTHER_SECRET"
          echo $SOME_OTHER_SECRET | base64
          python -c "import os,base64; print(base64.b64encode(os.environ['SOME_OTHER_SECRET']).encode('ascii'))"
          echo "Using creds 'oauth/$SOME_OTHER_SECRET'"
          echo "$GITHUB_TOKEN"
          env
